### ISSUE TITLE
Nyaa plugins don't work

### ISSUE THREAD

**Issue by tylercson** [MadeOfMagicAndWires/qBit-plugins#11]
The plugins install without error but searches return zero results
![Screenshot 2022-06-26 144807](https://user-images.githubusercontent.com/108241128/175835008-bf423dfd-d025-43f9-a1ca-493bb0831987.png)

**Comment by creeper6530** [comment]
Do you have lastest Python version installed?

**Comment by MadeOfMagicAndWires** [comment]
Hey there, sorry for the late reply.

I can't seem to reproduce this bug on my own machine so could you provide a little more information? 
Which plugin version are you using, does visiting the site manually provide results for you,  and does your Execution Log say anything relevant? (you can show the execution log through `View` -> `Log` and checking `Show`), and like creeper said could you report your python version by running `python -V` in the command line?

Finally, this is maybe a bit much to ask but it'd also really help me out if you could manually test the plugin using [test the plugin](https://github.com/qbittorrent/search-plugins/wiki/How-to-write-a-search-plugin#testing-your-plugin) with the same input and report any output.

**Comment by MadeOfMagicAndWires** [comment]
Closing this for now, let me know if the issue persists
