### ISSUE TITLE
Use `.torrent` URL instead of magnet link for nyaa

### ISSUE THREAD

**Issue by zajimumaaa** [MadeOfMagicAndWires/qBit-plugins#13]
Looks like downloading from nyaa plugin search result will use magnet link. Could you change it to `.torrent` URL ? As far as I know the `.torrent` URL is always `nyaa.si/download/XXX.torrent` where `XXX` is from `nyaa.si/view/XXX`.

When I want to only download certain file from nyaa, I won't start the torrent automatically because I will choose the file in `content` tab. If magnet link is used, the file in `content` tab is not shown up unless I start the download for couple seconds. but if I do this some of the file will be downloaded partially (sometimes a lot). If `.torrent` URL is used the file in `content` tab is shown up without need to start the torrent first.

Or there's a way to use the magnet link and also get the file list without starting the torrent ?

**Comment by MadeOfMagicAndWires** [comment]
I've implemented a way to do this with aa56385. I'll keep magnet links the default, as they are less vulnerable to link-rot and the like but you can now set the plugin to download torrent files instead with a few extra steps.

Please update your plugin to the latest version and see [these steps](https://github.com/MadeOfMagicAndWires/qBit-plugins#downloading-torrent-files-instead-of-magnet-links) to change your settings.
 
I've tested things on my end, but do let me know how it goes 👍

**Comment by zajimumaaa** [comment]
> I've tested things on my end, but do let me know how it goes 👍

Thanks, it's also working fine on my end.

**Comment by zajimumaaa** [comment]
Could you also do this for sukebei ? the logic is the same as far as I know

**Comment by MadeOfMagicAndWires** [comment]
ah yeah I always forget about that. Will do.
