### ISSUE TITLE
add nyaa sukebei support

### ISSUE THREAD

**Issue by ghost** [MadeOfMagicAndWires/qBit-plugins#6]
https://sukebei.nyaa.net
https://sukebei.nyaa.si

**Comment by MadeOfMagicAndWires** [comment]
Hey sayo,

Sorry for the late reply. I'm afraid I am currently a bit busy with personal stuff, but I'll look into this in the near future. Feel free to remind me of this at a later point if it takes too long or to make a pull request if that is within your ability.

You could also use [phuongtailtranminh's plugin](https://github.com/phuongtailtranminh/qBittorrent-Nyaa-Search-Plugin/) as an alternative in the meantime.

**Comment by Obegg** [comment]
Hey @MadeOfMagicAndWires 
Found an easy fix for sukebei, basically clone the original nyaa, and only change the URL.
Since both are very similar - it works.

**Comment by Obegg** [comment]
There you go, created a PR.
https://github.com/MadeOfMagicAndWires/qBit-plugins/pull/10
