### ISSUE TITLE
Proxy server

### ISSUE THREAD

**Issue by s4nket** [MadeOfMagicAndWires/qBit-plugins#7]
How can I make the plugin visit the website using a proxy? because nyaa.si is blocked in my country and I don't like turning on vpn just for this and proxy switcher also messes up with other browser tabs.

**Comment by MadeOfMagicAndWires** [comment]
I can't be certain without knowing the proxy but if it's a one-on-one replacement you should be able to download the nyaa.si engine file and change the following 

https://github.com/MadeOfMagicAndWires/qBit-plugins/blob/0b205fc432a11835861489342ee6e3f92cd2ab69/engines/nyaasi.py#L32-L35

to read `url = 'https://yourproxysitehere.com'`.

If that doesn't work let me know which site you are using and I'll take a look at it.

**Comment by s4nket** [comment]
Thank you for replying and the suggestion.
But I am not using a proxy site (nyaa.net) but a free proxy server to access nyaa.si/sukebei.nyaa.si on my browser, so I thought I could get this plugin to do the same but after experimenting I don't think it is possible for just this plugin to use a proxy server as socks.py is used by all the engines, I also tried enabling the qbittorrent proxy but that also made the other search engines and the rss slow, so I think I will continue visiting the website through my browser only. ;(

**Comment by MadeOfMagicAndWires** [comment]
I'll see if I can take a look at it some time. Bit busy for the month though, so don't hold your breath.

**Comment by s4nket** [comment]
Would be a big help, Thanks!
