### ISSUE TITLE
Plugin bakabt is not supported.

### ISSUE THREAD

**Issue by BloodyMikey** [MadeOfMagicAndWires/qBit-plugins#8]
Plugin bakabt is not supported.
qBittorrent/4.3.8

**Comment by MadeOfMagicAndWires** [comment]
I'll  take a look at this, but can you be a bit more specific by what you mean by "supported"? 

Did you have issues installing it, or does it not return results?

**Comment by BloodyMikey** [comment]
This is what in the logs when i try to add it

**Comment by MadeOfMagicAndWires** [comment]
I'll take a look at it, thanks for the heads up
